# Generated by Django 3.2.3 on 2021-05-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_path',
            field=models.FilePathField(default='C:\\Users\\Ravula\\projects\\spotifyClone\\spotify\\static\\music', path='C:\\Users\\Ravula\\projects\\spotifyClone\\spotify\\static\\music', recursive=True),
        ),
    ]
