# Generated by Django 3.2.3 on 2021-05-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_music_music_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_path',
            field=models.CharField(max_length=200),
        ),
    ]
