# Generated by Django 3.2.3 on 2021-05-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_playlists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playlists',
            new_name='Playlist',
        ),
    ]
