# Generated by Django 3.2.3 on 2021-05-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_rename_playlists_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.IntegerField()),
                ('music_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='music',
        ),
    ]
