# Generated by Django 3.2.3 on 2021-05-17 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_auto_20210517_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistmusic',
            name='music_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.music'),
        ),
        migrations.AlterField(
            model_name='playlistmusic',
            name='playlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.playlist'),
        ),
    ]
