# Generated by Django 3.2.3 on 2021-05-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0010_auto_20210519_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistmusic',
            old_name='music_id',
            new_name='music',
        ),
        migrations.RenameField(
            model_name='playlistmusic',
            old_name='playlist_id',
            new_name='playlist',
        ),
    ]
