# Generated by Django 3.2.3 on 2021-05-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0011_auto_20210519_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistmusic',
            name='music',
        ),
        migrations.AddField(
            model_name='playlist',
            name='music',
            field=models.ManyToManyField(to='spotify.Music'),
        ),
    ]
