# Generated by Django 3.2.3 on 2021-05-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0012_auto_20210519_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='PlaylistMusic',
        ),
    ]
