# Generated by Django 3.2.3 on 2021-05-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0013_auto_20210520_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='top_artist',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='music',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='img',
        ),
        migrations.AddField(
            model_name='playlist',
            name='created_by',
            field=models.CharField(default=False, max_length=30),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='playlist',
        #     name='image',
        #     field=models.CharField(blank=True, max_length=256),
        # ),
    ]
