# Generated by Django 3.2.3 on 2021-05-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0014_auto_20210521_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
