# Generated by Django 3.2.3 on 2021-05-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0017_auto_20210521_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='createplaylist',
            name='img',
            field=models.ImageField(default=False, upload_to=''),
            preserve_default=False,
        ),
    ]
