# Generated by Django 3.2.3 on 2021-05-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0018_createplaylist_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='created_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
