# Generated by Django 3.2.3 on 2021-05-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0019_auto_20210521_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='created_by',
        ),
    ]
