# Generated by Django 3.2.3 on 2021-06-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0027_music_album_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='album_cover',
        ),
    ]
