# Generated by Django 3.2.3 on 2021-06-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0028_remove_music_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_path',
            field=models.CharField(max_length=500),
        ),
    ]
