# Generated by Django 3.2.3 on 2021-06-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0029_alter_music_music_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='music',
            field=models.ManyToManyField(blank=True, to='spotify.Music'),
        ),
    ]
