# Generated by Django 3.2.3 on 2021-06-17 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify', '0030_alter_playlist_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='is_liked',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
