# Generated by Django 3.2.3 on 2021-06-28 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify', '0035_alter_playlist_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='liked_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
