# Generated by Django 3.2.3 on 2021-07-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0037_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
